name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          

      # (Optional) Ensure Ant is present. Remove if your runner already has Ant.
      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Build the JAR
        run: ant -noinput -buildfile build.xml export_jar

      - name: Run JUnit tests
        run: ant -noinput -buildfile build.xml test
      
